# Generated by Django 4.0 on 2024-04-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totine_of_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rolee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
            ],
        ),
    ]
