# Generated by Django 4.0 on 2024-04-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totine_of_app', '0006_membre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupetontinee',
            name='date_decréation',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
