# Generated by Django 4.0 on 2024-04-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totine_of_app', '0012_membree_delete_membre'),
    ]

    operations = [
        migrations.CreateModel(
            name='contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='contributions',
        ),
    ]
