# Generated by Django 4.0 on 2024-04-29 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totine_of_app', '0014_contributionn_delete_contribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributionn',
            name='montant_cotribution',
        ),
    ]
