# Generated by Django 4.0 on 2024-05-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totine_of_app', '0015_remove_contributionn_montant_cotribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='groupe_tontine',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='utilisateur',
        ),
    ]
