# Generated by Django 4.0 on 2024-05-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totine_of_app', '0016_remove_paiement_groupe_tontine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='paiements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('montant_paiement', models.CharField(max_length=150)),
                ('date_paeiement', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='paiement',
        ),
    ]
